name: Yeetcode

services:
  db:
    container_name: yeetcode-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/data

  # Redis
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379" # Redis server port
      - "8001:8001" # RedisInsight UI port
    volumes:
      - redis_data:/data # Persist data

  worker:
    build:
      context: ./code-executor-worker
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - db
      - redis
volumes:
  redis-data:
  postgres_data:
