name: Yeetcode

services:
  db:
    container_name: yeetcode-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/data

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  worker:
    build:
      context: ./code-executor-worker
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - db
      - redis
volumes:
  redis-data:
  postgres_data:
