name: Yeetcode

services:

  # Nginix Reverse Proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Exposing NGINX service on port 80
    # networks:
    #   - app-network


  # Postgres or whatever 
  db:
    container_name: yeetcode-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - postgres_data:/data

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  # Nextjs
  client:

  # Microservice 1
  problem-service:

  # Microservice 2
  evaluation-service:

  # Bullmq worker
  worker:


volumes:
  redis-data:
  postgres_data:
